{% set name = "eo-dataflow-ui" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/eo-dataflow/eo-dataflow-ui/-/archive/{{ version }}/eo-dataflow-ui-{{ version }}.tar.gz
  sha256: eb63d052adeee7e23aaa7fdd7dd227e638b5054adfc057d45eea03f64edddb95

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - poetry
    - poetry-dynamic-versioning
    - pip
  run:
    - python
    - django >=1.11,<2.0
    - lxml >=4.4.1
    - celery <5
    - simplejson >=3,<4
    - requests <3.0.0
    - ruamel.yaml >=0.16.13

test:
  imports:
    - eo_dataflow_ui

about:
  home: https://gitlab.ifremer.fr/eo-dataflow/eo-dataflow-ui
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Web UI for monitoring and administering the eo-dataflow manager.

extra:
  recipe-maintainers:
    - 2x38
    - marie59
